<?php

declare(strict_types=1);

namespace Gyrobus\MoonshineStaticData\Pages;

use Closure;
use Gyrobus\MoonshineStaticData\Models\StaticData;
use Gyrobus\MoonshineStaticData\Resources\StaticDataResource;
use Gyrobus\MoonshineCropper\Fields\Cropper;
use MoonShine\Laravel\Fields\Slug;
use MoonShine\Laravel\Http\Responses\MoonShineJsonResponse;
use MoonShine\Laravel\MoonShineRequest;
use MoonShine\Laravel\Pages\Page;
use MoonShine\Contracts\UI\ComponentContract;
use MoonShine\Laravel\TypeCasts\ModelCaster;
use MoonShine\Support\Enums\FormMethod;
use MoonShine\Support\Enums\ToastType;
use MoonShine\TinyMce\Fields\TinyMce;
use MoonShine\UI\Components\FormBuilder;
use MoonShine\UI\Components\Layout\Box;
use MoonShine\UI\Components\Tabs;
use MoonShine\UI\Components\Tabs\Tab;
use MoonShine\UI\Fields\File;
use MoonShine\UI\Fields\Hidden;
use MoonShine\UI\Fields\Image;
use MoonShine\UI\Fields\Json;
use MoonShine\UI\Fields\Number;
use MoonShine\UI\Fields\Phone;
use MoonShine\UI\Fields\Text;
use MoonShine\UI\Fields\Textarea;

class GroupForm extends Page
{
    /**
     * @return array<string, string>
     */
    public function getBreadcrumbs(): array
    {
        return [
            toPage(GroupIndex::class, StaticDataResource::class) => __('moonshine-static-data::main.title'),
            '#' => __('moonshine-static-data::main.addGroup')
        ];
    }

    public function getTitle(): string
    {
        return __('moonshine-static-data::main.addGroup');
    }

    protected function prepareBeforeRender(): void
    {
        parent::prepareBeforeRender(); // TODO: Change the autogenerated stub

        if (!config('moonshine-static-data.create_group')) {
            oops404();
        }
    }

    /**
     * @return list<ComponentContract>
     */
    protected function components(): iterable
	{
		return [
            Box::make([
                FormBuilder::make()
                    ->fields([
                        Text::make(__('moonshine-static-data::main.groupName'), 'name')
                            ->reactive()
                            ->required(),
                        Slug::make(__('moonshine-static-data::main.groupSlug'), 'slug')
                            ->unique()
                            ->from('name')
                            ->live()
                            ->required(),
                    ])
                    ->asyncMethod('createGroup')
            ])
        ];
	}
}
